# Generated by Django 6.0.3 on 2026-03-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('Happy', 'Happy 😊'), ('Sad', 'Sad 😢'), ('Angry', 'Angry 😡'), ('Stressed', 'Stressed 😰'), ('Calm', 'Calm 😌')], max_length=20)),
                ('text', models.TextField()),
            ],
        ),
    ]
